import "../styles/globals.css";
import "../styles/locomotiv-scroll.css";
import { useRef } from "react";
import Head from "next/head";
import { LocomotiveScrollProvider } from "react-locomotive-scroll";
const MyApp = ({ Component, pageProps }) => {
  const containerRef = useRef(null);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/PrestoWide.otf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <header>header</header>
      <LocomotiveScrollProvider
        options={{
          smooth: true,
        }}
        watch={[]}
        containerRef={containerRef}
      >
        <main data-scroll-container ref={containerRef}>
          <Component {...pageProps} />
        </main>
      </LocomotiveScrollProvider>
      <footer>footer</footer>
    </div>
  );
};
export default MyApp;
