import "../styles/globals.css";

import "../styles/locomotiv-scroll.css";
import { useRef, useEffect, useState } from "react";
import Head from "next/head";
import Header from "../components/header/header";
import "../components/header/header.css";
import "../components/hero-section/hero.css";
import "../components/about/about.css";
import { LocomotiveScrollProvider } from "react-locomotive-scroll";
import { darkModeDetection } from "../utils/DarkMode";
import { pixelAnimation } from "../components/hero-section/pixel-bg";
import { ChangeBgColor, ResetBgColor } from "../utils/ChangeBgColor";

const MyApp = ({ Component, pageProps }) => {
  const containerRef = useRef(null);
  useEffect(() => {
    darkModeDetection();
  }, []);

  const [crazy, setCrazy] = useState(false);

  // if crazy is true, turns page crazy
  useEffect(() => {
    if (crazy) {
      pixelAnimation(true);
      ChangeBgColor();
    } else {
      ResetBgColor();
    }
  }, [crazy]);

  return (
    <div>
      <Head>
        <title>Portfolio - Adrien Sosa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/PrestoWide.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/PrestoLight.otf"
          as="font"
          crossOrigin=""
        />
        <link
          rel="preload"
          href="/fonts/PrestoExtended.otf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <LocomotiveScrollProvider
        options={{
          smooth: true,
        }}
        watch={[]}
        containerRef={containerRef}
      >
        <main
          data-scroll-container
          className="bg-beige-regular dark:bg-black text-black dark:text-beige-regular"
          ref={containerRef}
        >
          <Header setCrazy={setCrazy} crazy={crazy} />
          <Component {...pageProps} />
          <footer data-scroll-section>footer</footer>
        </main>
      </LocomotiveScrollProvider>
    </div>
  );
};
export default MyApp;
