import "../styles/globals.css";
import "../styles/locomotiv-scroll.css";
import { useRef, useEffect } from "react";
import Head from "next/head";
import Header from "../components/header/header";
import "../components/header/header.css";
import { LocomotiveScrollProvider } from "react-locomotive-scroll";
import { isDarkMode } from "../utils/DarkMode";
const MyApp = ({ Component, pageProps }) => {
  const containerRef = useRef(null);
  useEffect(() => {
    isDarkMode();
  }, []);

  return (
    <div>
      <Head>
        <title>Portfolio - Adrien Sosa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="preload"
          href="/fonts/PrestoWide.otf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <LocomotiveScrollProvider
        options={{
          smooth: true,
        }}
        watch={[]}
        containerRef={containerRef}
      >
        <main
          data-scroll-container
          className="bg-beige-regular dark:bg-black text-black dark:text-beige-regular"
          ref={containerRef}
        >
          <Header />
          <Component {...pageProps} />
          <footer data-scroll-section>footer</footer>
        </main>
      </LocomotiveScrollProvider>
    </div>
  );
};
export default MyApp;
