import Head from "next/head";
import { useLocomotiveScroll } from "react-locomotive-scroll";
import { useEffect } from "react";
import {
  PrismicText,
  useFirstPrismicDocument,
  useAllPrismicDocumentsByType,
} from "@prismicio/react";
const Home: any = () => {
  const { scroll } = useLocomotiveScroll();
  // const [documents] = useAllPrismicDocumentsByType("projects");
  const [document] = useFirstPrismicDocument();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div data-scroll-container>
          <div className="first" data-scroll-section>
            <div data-scroll data-scroll-speed="4" data-scroll-position="top">
              <h1>Front-end Developer</h1>
            </div>
            <h2>
              <span data-scroll data-scroll-delay="0.15" data-scroll-speed="3">
                S
              </span>
              <span data-scroll data-scroll-delay="0.20" data-scroll-speed="3">
                O
              </span>
              <span data-scroll data-scroll-delay="0.25" data-scroll-speed="3">
                S
              </span>
              <span data-scroll data-scroll-delay="0.30" data-scroll-speed="3">
                A
              </span>
            </h2>
          </div>
          <div data-scroll-section>
            <h1 data-scroll data-scroll-speed="1">
              Hey
            </h1>
            <p>fdfdf</p>
          </div>
          <div data-scroll-section>
            <h1 data-scroll id="hey" data-scroll-speed="1">
              Hey
            </h1>
            <p>fdfdf</p>
          </div>
          <div data-scroll-section>
            <h1 data-scroll id="hey" data-scroll-speed="1">
              Hey
            </h1>
            <p>fdfdf</p>
          </div>
        </div>
        <div>{document && <PrismicText field={document.data.name} />}</div>
      </main>

      <footer>footer</footer>
    </div>
  );
};

export default Home;
